# Generated by Django 5.2.3 on 2025-06-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountdeletelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeletelog',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
