# Generated by Django 5.2.3 on 2025-06-26 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_briffingpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BriffingPost',
        ),
    ]
