# Generated by Django 5.2.3 on 2025-06-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_alter_discussion_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='group_name',
            field=models.DateTimeField(max_length=255),
        ),
    ]
